name: GHAS CSV Report upload workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'GeekMasher/ghas-csv'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests
    - name: Generate GHAS CSV Report
      run: |
        python3 ghas-csv.py -r ${{ github.repository }} -t ${{ github.token }}
    - uses: actions/upload-artifact@v2
      with:
        name: ghas-csv-report
        path: alerts.csv
